# Generated by Django 6.0.4 on 2026-05-07 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('estaca', models.CharField(max_length=120)),
                ('codigo', models.CharField(blank=True, max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObraMisional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacion', models.CharField(blank=True, choices=[('QUORUM', 'Quórum de Élderes'), ('SOCSOC', 'Sociedad de Socorro'), ('HOMBRES', 'Hombres Jóvenes'), ('MUJERES', 'Mujeres Jóvenes'), ('PRIMARIA', 'Primaria')], max_length=20, null=True)),
                ('condicion_actual', models.CharField(blank=True, choices=[('MENOS_ACTIVOS', 'Menos activos'), ('ACTIVOS', 'Activos'), ('CONVERSOS', 'Conversos'), ('INVESTIGADORES', 'Investigadores')], max_length=20, null=True)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('meta', models.CharField(blank=True, max_length=50, null=True)),
                ('ordenanza_faltante', models.CharField(blank=True, choices=[('BAUTISMO', 'Bautismo'), ('INVESTIDURA', 'Investidura'), ('SELLAMIENTO', 'Sellamiento')], max_length=50, null=True)),
                ('fecha_meta', models.DateField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('barrio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barrio.barrio')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('organizacion', models.CharField(choices=[('QUORUM', 'Quórum de Élderes'), ('SOCSOC', 'Sociedad de Socorro'), ('HOMBRES', 'Hombres Jóvenes'), ('MUJERES', 'Mujeres Jóvenes'), ('PRIMARIA', 'Primaria')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barrio.barrio')),
            ],
        ),
    ]
