# Generated by Django 5.2.6 on 2025-11-12 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObraMisional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacion', models.CharField(blank=True, choices=[('QUORUM', 'Quorum de Elderes'), ('SOCSOC', 'Sociedad de Socorro'), ('MUJERES', 'Mujeres Jóvenes'), ('HOMBRES', 'Hombres Jóvenes'), ('PRIMARIA', 'Primaria')], max_length=100, null=True, verbose_name='Organizacion')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('fecha_establecida', models.DateField(blank=True, null=True, verbose_name='Fecha Establecida')),
                ('fecha_meta', models.DateField(blank=True, null=True, verbose_name='Fecha de Meta')),
                ('done', models.BooleanField(default=False, verbose_name='Completado')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Nota')),
                ('condicion_actual', models.CharField(blank=True, choices=[('INVESTIGADOR', 'Investigador'), ('CONVERSO', 'Converso'), ('LESSACTIVE', 'Menos Activo')], max_length=100, null=True, verbose_name='Condición Actual')),
                ('ordenanza_faltante', models.CharField(blank=True, choices=[('BAUSTISMO', 'Bautismo'), ('VICARIO', 'Bautismo Vicario'), ('INVESTIDURA', 'Investidura'), ('SELLAMIENTO', 'Sellamiento')], max_length=100, null=True, verbose_name='Ordenanza Faltante')),
            ],
        ),
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('fecha_meta', models.DateField(blank=True, null=True, verbose_name='Fecha Meta')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barrio.obramisional', verbose_name='Obra Misional')),
            ],
        ),
    ]
