# Generated by Django 6.0.4 on 2026-05-07 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obramisional',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barrio.persona'),
        ),
    ]
