# Generated by Django 5.2.6 on 2025-11-14 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('fecha_meta', models.DateField(blank=True, null=True, verbose_name='Fecha Meta')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barrio.obramisional', verbose_name='Obra Misional')),
            ],
        ),
    ]
