# Generated by Django 5.2.6 on 2025-11-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrio', '0002_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metas',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='obramisional',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='obramisional',
            name='ordenanza_faltante',
        ),
        migrations.AddField(
            model_name='obramisional',
            name='meta',
            field=models.TextField(blank=True, null=True, verbose_name='Meta'),
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='Metas',
        ),
    ]
