# Generated by Django 6.0.4 on 2026-05-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrio', '0002_obramisional_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obramisional',
            name='condicion_actual',
        ),
        migrations.RemoveField(
            model_name='obramisional',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='obramisional',
            name='ordenanza_faltante',
        ),
        migrations.RemoveField(
            model_name='obramisional',
            name='organizacion',
        ),
        migrations.RemoveField(
            model_name='obramisional',
            name='persona',
        ),
        migrations.AddField(
            model_name='persona',
            name='condicion_actual',
            field=models.CharField(blank=True, choices=[('MENOS_ACTIVOS', 'Menos activos'), ('ACTIVOS', 'Activos'), ('CONVERSOS', 'Conversos'), ('INVESTIGADORES', 'Investigadores')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='ordenanza_faltante',
            field=models.CharField(blank=True, choices=[('BAUTISMO', 'Bautismo'), ('INVESTIDURA', 'Investidura'), ('SELLAMIENTO', 'Sellamiento')], max_length=50, null=True),
        ),
    ]
