# Generated by Django 5.2.6 on 2025-11-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrio', '0003_remove_metas_obra_remove_obramisional_nota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obramisional',
            name='ordenanza_faltante',
            field=models.CharField(blank=True, choices=[('BAUSTISMO', 'Bautismo'), ('VICARIO', 'Bautismo Vicario'), ('Activacion', 'Activación'), ('INVESTIDURA', 'Investidura'), ('SELLAMIENTO', 'Sellamiento')], max_length=100, null=True, verbose_name='Ordenanza Faltante'),
        ),
        migrations.AlterField(
            model_name='obramisional',
            name='condicion_actual',
            field=models.CharField(blank=True, choices=[('INVESTIGADOR', 'Investigador'), ('CONVERSO', 'Converso'), ('LESSACTIVE', 'Menos Activo'), ('ACTIVO', 'Activo')], max_length=100, null=True, verbose_name='Condición Actual'),
        ),
    ]
