# Generated by Django 6.0.4 on 2026-05-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrio', '0004_obramisional_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='obramisional',
            name='responsable',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
