# Generated by Django 5.2.6 on 2025-11-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrio', '0004_obramisional_ordenanza_faltante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=3, unique=True, verbose_name='PIN')),
                ('organizacion', models.CharField(max_length=50, verbose_name='Organización')),
            ],
        ),
    ]
