# Generated by Django 5.2.6 on 2025-11-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrio', '0005_loginuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='organizacion',
            field=models.CharField(choices=[('QUORUM', 'Quorum de Elderes'), ('SOCSOC', 'Sociedad de Socorro'), ('MUJERES', 'Mujeres Jóvenes'), ('HOMBRES', 'Hombres Jóvenes'), ('PRIMARIA', 'Primaria')], max_length=20, verbose_name='Organización'),
        ),
    ]
