# Generated by Django 6.0.4 on 2026-05-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrio', '0005_obramisional_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='obramisional',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
