# Generated by Django 5.2.6 on 2025-11-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrio', '0006_alter_loginuser_organizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='organizacion',
            field=models.CharField(choices=[('QUORUM', 'Quorum de Elderes'), ('SOCSOC', 'Sociedad de Socorro'), ('MUJERES', 'Mujeres Jóvenes'), ('HOMBRES', 'Hombres Jóvenes'), ('PRIMARIA', 'Primaria'), ('OBISPADO', 'Obispado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='pin',
            field=models.CharField(max_length=10, unique=True, verbose_name='PIN'),
        ),
    ]
