# Generated by Django 5.2.6 on 2025-11-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrio', '0007_alter_loginuser_organizacion_alter_loginuser_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.CharField(choices=[('MA_DOMINGOS4', 'Llegar 4 domingos consecutivos'), ('MA_ACTIVIDADES', 'Ir a actividades de la iglesia'), ('MA_HOGAR', 'Hacer noches de hogar'), ('MA_TEMPLO', 'Ir al templo'), ('MA_EDUCACION', 'Participar en programas de educación de la iglesia (BYU Pathway, Becas Benson, Fondo Perpetuo, Mentors)'), ('MA_ARBOL', 'Trabajar en su árbol familiar'), ('AC_AMIGOS', 'Hacerse de uno o más amigos recién conversos, investigadores o menos activos'), ('AC_TEMPLO', 'Ir al templo'), ('AC_MISIONEROS', 'Apoyar en las visitas con los misioneros'), ('AC_EDUCACION', 'Participar en programas de educación de la iglesia (BYU Pathway, Becas Benson, Fondo Perpetuo, Mentors)'), ('AC_ACTIVIDADES', 'Participar de las actividades de la iglesia'), ('AC_ORIENTAR', 'Orientar y apoyar a recién conversos, investigadores y menos activos'), ('AC_LIMPIEZA', 'Apoyar en la limpieza de nuestra capilla'), ('AC_HOGAR', 'Hacer noches de hogar'), ('CV_ARBOL', 'Trabajar en su árbol (historia familiar)'), ('CV_TEMPLO', 'Ir al templo'), ('CV_HOGAR', 'Hacer noches de hogar'), ('CV_ACTIVIDADES', 'Participar en las actividades de la iglesia'), ('CV_DOMINGOS', 'Llegar todos los domingos conforme sus posibilidades lo permitan'), ('CV_EDUCACION', 'Participar en programas de educación de la iglesia (BYU Pathway, Becas Benson, Fondo Perpetuo, Mentors)'), ('CV_CLASES', 'Aprender a dar clases'), ('QS_AUTOSUFICIENCIA', 'Participar en cursos de autosuficiencia'), ('QS_BAUTIZOS_JOVENES', 'Durante el primer año, participar con los jóvenes en bautizos en el templo'), ('QS_ORDENANZAS', 'Luego del primer año hacer ordenanzas mayores (investidura, sellamiento)'), ('JOV_LEMA', 'Aprenderse el lema de HJ/MJ'), ('INV_LIBRO_MORMON', 'Leerse el Libro de Mormón'), ('INV_ESCRITURAS', 'Leerse las escrituras'), ('INV_DOMINGOS3', 'Asistir a 3 domingos consecutivos'), ('INV_ACTIVIDADES', 'Llegar a actividades del barrio'), ('INV_AMIGO', 'Hacerse de un amigo'), ('INV_TEMPLO', 'Ir al templo')], max_length=50, verbose_name='Meta')),
            ],
        ),
        migrations.DeleteModel(
            name='LoginUser',
        ),
    ]
