# Generated by Django 5.2.6 on 2025-11-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrio', '0008_meta_delete_loginuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meta',
            options={'managed': False, 'verbose_name': 'Meta', 'verbose_name_plural': 'Metas'},
        ),
        migrations.AlterField(
            model_name='obramisional',
            name='condicion_actual',
            field=models.CharField(blank=True, choices=[('MENOS_ACTIVOS', 'Menos activos'), ('ACTIVOS', 'Activos'), ('CONVERSOS', 'Conversos'), ('QUORUM', 'Quórum (varón)'), ('SOCSOC', 'Sociedad de Socorro (mujer)'), ('HOMBRES', 'Hombres Jóvenes'), ('MUJERES', 'Mujeres Jóvenes'), ('INVESTIGADORES', 'Investigadores')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='obramisional',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='obramisional',
            name='fecha_establecida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obramisional',
            name='fecha_meta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obramisional',
            name='meta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='obramisional',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='obramisional',
            name='ordenanza_faltante',
            field=models.CharField(blank=True, choices=[('BAUTISMO', 'Bautismo'), ('INVESTIDURA', 'Investidura'), ('SELLAMIENTO', 'Sellamiento')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='obramisional',
            name='organizacion',
            field=models.CharField(blank=True, choices=[('QUORUM', 'Quórum de Élderes'), ('SOCSOC', 'Sociedad de Socorro'), ('HOMBRES', 'Hombres Jóvenes'), ('MUJERES', 'Mujeres Jóvenes'), ('PRIMARIA', 'Primaria')], max_length=20, null=True),
        ),
    ]
