# Generated by Django 5.2.6 on 2025-11-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrio', '0009_alter_meta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obramisional',
            name='condicion_actual',
            field=models.CharField(blank=True, choices=[('MENOS_ACTIVOS', 'Menos activos'), ('ACTIVOS', 'Activos'), ('CONVERSOS', 'Conversos'), ('INVESTIGADORES', 'Investigadores')], max_length=20, null=True),
        ),
    ]
