# Generated by Django 5.2.6 on 2025-11-26 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barrio', '0010_alter_obramisional_condicion_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obramisional',
            name='fecha_establecida',
        ),
    ]
