# Generated by Django 6.0.4 on 2026-05-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrio', '0011_remove_obramisional_fecha_establecida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('estaca', models.CharField(max_length=120)),
                ('codigo', models.CharField(blank=True, max_length=4, unique=True)),
            ],
        ),
    ]
