# Generated by Django 6.0.4 on 2026-05-05 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrio', '0012_barrio'),
    ]

    operations = [
        migrations.AddField(
            model_name='obramisional',
            name='barrio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barrio.barrio'),
        ),
    ]
