# Generated by Django 6.0.4 on 2026-05-06 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barrio', '0013_obramisional_barrio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meta',
        ),
    ]
