# Generated by Django 6.0.4 on 2026-05-06 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrio', '0014_delete_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('organizacion', models.CharField(choices=[('QUORUM', 'Quórum de Élderes'), ('SOCSOC', 'Sociedad de Socorro'), ('HOMBRES', 'Hombres Jóvenes'), ('MUJERES', 'Mujeres Jóvenes'), ('PRIMARIA', 'Primaria')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barrio.barrio')),
            ],
        ),
    ]
